repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: rust-clippy
        name: Rust clippy
        description: Run cargo clippy on files included in the commit
        entry: cargo clippy --all-targets --all-features -- -Dclippy::all
        language: system
        pass_filenames: false
        types: [file, rust]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
