name: CI

on:
  pull_request:
    paths-ignore:
      - "**.rs"
      - Cargo.toml
  push:
    branches:
      - main
    paths-ignore:
      - "**.rs"
      - Cargo.toml

jobs:
  skip:
    name: Skip CI
    runs-on: ubuntu-latest
    steps:
      - run: echo 'No changes on Rust files'
